name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 4.0.1)'
        required: true
        default: ''
      dry-run:
        description: 'Dry run (no actual publishing)'
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update version if provided
        if: github.event.inputs.version != ''
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Build TypeScript
        run: npm run build:ts
        
      - name: Prepare Capacitor Plugin
        run: node scripts/prepare-capacitor.js
        
      - name: Prepare Cordova Plugin
        run: node scripts/prepare-cordova.js
      
      - name: Create package tarballs
        run: |
          cd dist/capacitor && npm pack
          cd ../cordova && npm pack
          
      - name: Upload package tarballs
        uses: actions/upload-artifact@v3
        with:
          name: npm-packages
          path: |
            dist/capacitor/*.tgz
            dist/cordova/*.tgz
        
      - name: Publish Capacitor Plugin to NPM
        if: github.event.inputs.dry-run != 'true'
        run: cd dist/capacitor && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish Cordova Plugin to NPM
        if: github.event.inputs.dry-run != 'true'
        run: cd dist/cordova && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publication Status
        run: |
          if [[ "${{ github.event.inputs.dry-run }}" == "true" ]]; then
            echo "✅ Dry run completed - packages were created but not published"
            echo "Download the artifacts to inspect the packages"
          else
            echo "✅ Packages successfully published to npm registry"
          fi
            echo "✅ Dry run completed - packages were created but not published"
            echo "Download the artifacts to inspect the packages"
          else
            echo "✅ Packages successfully published to npm registry"
          fi
