name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 4.0.1)'
        required: true
        default: ''
      publish-capacitor:
        description: 'Publish Capacitor plugin'
        type: boolean
        default: true
      publish-cordova:
        description: 'Publish Cordova plugin'
        type: boolean
        default: true
      dry-run:
        description: 'Dry run (no actual publishing)'
        type: boolean
        default: false

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download Capacitor artifact
        uses: actions/download-artifact@v4
        with:
          name: capacitor-plugin
          path: dist/capacitor

      - name: Download Cordova artifact
        uses: actions/download-artifact@v4
        with:
          name: cordova-plugin
          path: dist/cordova
      
      - name: Display downloaded files
        run: ls -R dist

      - name: Publish Capacitor Plugin to NPM
        if: ${{ github.event.inputs.dry-run != 'true' && github.event.inputs.publish-capacitor == 'true' }}
        run: |
          echo "Publishing Capacitor plugin..."
          cd dist/capacitor && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish Cordova Plugin to NPM
        if: ${{ github.event.inputs.dry-run != 'true' && github.event.inputs.publish-cordova == 'true' }}
        run: |
          echo "Publishing Cordova plugin..."
          cd dist/cordova && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      # Provide feedback at the end
      - name: Publication Status
        run: echo "Publication process completed"
      
      - name: Dry Run Status
        if: github.event.inputs.dry-run == 'true'
        run: echo "✅ Dry run completed - packages were not published"
      
      - name: Capacitor Publish Status
        if: github.event.inputs.dry-run == 'false' && github.event.inputs.publish-capacitor == 'true'
        run: echo "✅ Capacitor plugin published to npm registry"
      
      - name: Cordova Publish Status
        if: github.event.inputs.dry-run == 'false' && github.event.inputs.publish-cordova == 'true'
        run: echo "✅ Cordova plugin published to npm registry"
